/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ListingsIdRouteImport } from './routes/listings/$id'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminListingsIndexRouteImport } from './routes/admin/listings/index'
import { Route as AdminInquiriesIndexRouteImport } from './routes/admin/inquiries/index'
import { Route as AdminListingsNewRouteImport } from './routes/admin/listings/new'
import { Route as AdminListingsIdEditRouteImport } from './routes/admin/listings/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/admin/listings/',
  path: '/admin/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesIndexRoute = AdminInquiriesIndexRouteImport.update({
  id: '/admin/inquiries/',
  path: '/admin/inquiries/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/admin/listings/new',
  path: '/admin/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsIdEditRoute = AdminListingsIdEditRouteImport.update({
  id: '/admin/listings/$id/edit',
  path: '/admin/listings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminLayoutRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings': typeof ListingsIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/inquiries': typeof AdminInquiriesIndexRoute
  '/admin/listings': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/listings/$id'
    | '/admin/'
    | '/listings/'
    | '/admin/listings/new'
    | '/admin/inquiries/'
    | '/admin/listings/'
    | '/admin/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/listings/$id'
    | '/listings'
    | '/admin/listings/new'
    | '/admin/inquiries'
    | '/admin/listings'
    | '/admin/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/_layout'
    | '/listings/$id'
    | '/admin/'
    | '/listings/'
    | '/admin/listings/new'
    | '/admin/inquiries/'
    | '/admin/listings/'
    | '/admin/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  ListingsIdRoute: typeof ListingsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
  AdminInquiriesIndexRoute: typeof AdminInquiriesIndexRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
  AdminListingsIdEditRoute: typeof AdminListingsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/admin/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries/': {
      id: '/admin/inquiries/'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminInquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/admin/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/$id/edit': {
      id: '/admin/listings/$id/edit'
      path: '/admin/listings/$id/edit'
      fullPath: '/admin/listings/$id/edit'
      preLoaderRoute: typeof AdminListingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  ListingsIdRoute: ListingsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
  AdminInquiriesIndexRoute: AdminInquiriesIndexRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
  AdminListingsIdEditRoute: AdminListingsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
